---
- name: Configure Nginx on Public Server
  hosts: aws_ec2
  become: yes 
  roles:
    - nginx

- name: Configure Elasticsearch and Kibana on Private Server
  hosts: aws_ec2
  become: yes 
  roles:
    - elasticsearch_kibana
