---
- name: Configure Nginx on Public Server
  hosts: aws_ec2  # Use 'all' to target all instances in the inventory
  become: yes
  roles:
    - nginx


# - name: Configure Elasticsearch and Kibana on Private Server
#   hosts: all
#   become: yes 
#   roles:
#     - elasticsearch_kibana
