---
- name: Configure Nginx on Public Server
  hosts: public
  become: yes 
  roles:
    - nginx

- name: Configure Elasticsearch and Kibana on Private Server
  hosts: private
  become: yes 
  roles:
    - elasticsearch_kibana
