---
- name: Configure Nginx on Public Server
  hosts: public_ip_address
  become: yes 
  roles:
    - nginx

# - name: Configure Elasticsearch and Kibana on Private Server
#   hosts: all
#   become: yes 
#   roles:
#     - elasticsearch_kibana
